# Generated by Django 5.1.1 on 2024-10-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_comment_parent_comment_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nestedcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='nestedcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='NestedComment',
        ),
    ]
