export const RECIPE_LIST_REQUEST = "RECIPE_LIST_REQUEST"
export const RECIPE_LIST_SUCCESS = "RECIPE_LIST_SUCCESS"
export const RECIPE_LIST_FAIL = "RECIPE_LIST_FAIL"

export const RECIPE_DETAILED_REQUEST = 'RECIPE_DETAILED_REQUEST';
export const RECIPE_DETAILED_SUCCESS = 'RECIPE_DETAILED_SUCCESS';
export const RECIPE_DETAILED_FAIL = 'RECIPE_DETAILED_FAIL';

export const RECIPE_CREATE_REQUEST = 'RECIPE_CREATE_REQUEST';
export const RECIPE_CREATE_SUCCESS = 'RECIPE_CREATE_SUCCESS';
export const RECIPE_CREATE_FAIL = 'RECIPE_CREATE_FAIL';


export const BOOKMARK_LIST_REQUEST = 'BOOKMARK_LIST_REQUEST';
export const BOOKMARK_LIST_SUCCESS = 'BOOKMARK_LIST_SUCCESS';
export const BOOKMARK_LIST_FAIL = 'BOOKMARK_LIST_FAIL';

export const GET_OWN_RECIPES_REQUEST = 'GET_OWN_RECIPES_REQUEST';
export const GET_OWN_RECIPES_SUCCESS = 'GET_OWN_RECIPES_SUCCESS';
export const GET_OWN_RECIPES_FAIL = 'GET_OWN_RECIPES_FAIL';