export const RECIPE_LIST_REQUEST = "RECIPE_LIST_REQUEST"
export const RECIPE_LIST_SUCCESS = "RECIPE_LIST_SUCCESS"
export const RECIPE_LIST_FAIL = "RECIPE_LIST_FAIL"

export const RECIPE_DETAILED_REQUEST = 'RECIPE_DETAILED_REQUEST';
export const RECIPE_DETAILED_SUCCESS = 'RECIPE_DETAILED_SUCCESS';
export const RECIPE_DETAILED_FAIL = 'RECIPE_DETAILED_FAIL';