export const RECIPE_LIST_REQUEST = "RECIPE_LIST_REQUEST"
export const RECIPE_LIST_SUCCESS = "RECIPE_LIST_SUCCESS"
export const RECIPE_LIST_FAIL = "RECIPE_LIST_FAIL"

export const RECIPE_DETAILED_REQUEST = 'RECIPE_DETAILED_REQUEST';
export const RECIPE_DETAILED_SUCCESS = 'RECIPE_DETAILED_SUCCESS';
export const RECIPE_DETAILED_FAIL = 'RECIPE_DETAILED_FAIL';

export const RECIPE_CREATE_REQUEST = 'RECIPE_CREATE_REQUEST';
export const RECIPE_CREATE_SUCCESS = 'RECIPE_CREATE_SUCCESS';
export const RECIPE_CREATE_FAIL = 'RECIPE_CREATE_FAIL';


export const BOOKMARK_LIST_REQUEST = 'BOOKMARK_LIST_REQUEST';
export const BOOKMARK_LIST_SUCCESS = 'BOOKMARK_LIST_SUCCESS';
export const BOOKMARK_LIST_FAIL = 'BOOKMARK_LIST_FAIL';

export const GET_OWN_RECIPES_REQUEST = 'GET_OWN_RECIPES_REQUEST';
export const GET_OWN_RECIPES_SUCCESS = 'GET_OWN_RECIPES_SUCCESS';
export const GET_OWN_RECIPES_FAIL = 'GET_OWN_RECIPES_FAIL';


export const BOOKMARK_RECIPE_REQUEST = 'BOOKMARK_RECIPE_REQUEST';
export const BOOKMARK_RECIPE_SUCCESS = 'BOOKMARK_RECIPE_SUCCESS';
export const BOOKMARK_RECIPE_FAIL = 'BOOKMARK_RECIPE_FAIL';

export const REMOVE_BOOKMARK_REQUEST = 'REMOVE_BOOKMARK_REQUEST';
export const REMOVE_BOOKMARK_SUCCESS = 'REMOVE_BOOKMARK_SUCCESS';
export const REMOVE_BOOKMARK_FAIL = 'REMOVE_BOOKMARK_FAIL';


export const RECIPE_CREATE_RESET = 'RECIPE_CREATE_RESET';


export const FOOD_OF_THE_WEEK_REQUEST = 'FOOD_OF_THE_WEEK_REQUEST';
export const FOOD_OF_THE_WEEK_SUCCESS = 'FOOD_OF_THE_WEEK_SUCCESS';
export const FOOD_OF_THE_WEEK_FAIL = 'FOOD_OF_THE_WEEK_FAIL';

export const FOOD_OF_THE_MONTH_REQUEST = 'FOOD_OF_THE_MONTH_REQUEST';
export const FOOD_OF_THE_MONTH_SUCCESS = 'FOOD_OF_THE_MONTH_SUCCESS';
export const FOOD_OF_THE_MONTH_FAIL = 'FOOD_OF_THE_MONTH_FAIL';


export const RANDOM_RECIPE_REQUEST = 'RANDOM_RECIPE_REQUEST';
export const RANDOM_RECIPE_SUCCESS = 'RANDOM_RECIPE_SUCCESS';
export const RANDOM_RECIPE_FAIL = 'RANDOM_RECIPE_FAIL';

export const RECIPE_DELETE_REQUEST = 'RECIPE_DELETE_REQUEST';
export const RECIPE_DELETE_SUCCESS = 'RECIPE_DELETE_SUCCESS';
export const RECIPE_DELETE_FAIL = 'RECIPE_DELETE_FAIL';


export const USER_RECIPES_REQUEST = 'USER_RECIPES_REQUEST';
export const USER_RECIPES_SUCCESS = 'USER_RECIPES_SUCCESS';
export const USER_RECIPES_FAIL = 'USER_RECIPES_FAIL';


export const RECIPE_UPDATE_REQUEST = 'RECIPE_UPDATE_REQUEST'
export const RECIPE_UPDATE_SUCCESS = 'RECIPE_UPDATE_SUCCESS'
export const RECIPE_UPDATE_FAIL = 'RECIPE_UPDATE_FAIL'
export const RECIPE_UPDATE_RESET = 'RECIPE_UPDATE_RESET'