export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'


export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';


export const GET_FOLLOWING_LIST_REQUEST = 'GET_FOLLOWING_LIST_REQUEST';
export const GET_FOLLOWING_LIST_SUCCESS = 'GET_FOLLOWING_LIST_SUCCESS';
export const GET_FOLLOWING_LIST_FAIL = 'GET_FOLLOWING_LIST_FAIL';


export const USER_COMMENTS_REQUEST = 'USER_COMMENTS_REQUEST';
export const USER_COMMENTS_SUCCESS = 'USER_COMMENTS_SUCCESS';
export const USER_COMMENTS_FAIL = 'USER_COMMENTS_FAIL';

export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST';
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS';
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL';

export const USER_UNFOLLOW_REQUEST = 'USER_UNFOLLOW_REQUEST';
export const USER_UNFOLLOW_SUCCESS = 'USER_UNFOLLOW_SUCCESS';
export const USER_UNFOLLOW_FAIL = 'USER_UNFOLLOW_FAIL';


export const FORUM_POST_CREATE_REQUEST = 'FORUM_POST_CREATE_REQUEST'
export const FORUM_POST_CREATE_SUCCESS = 'FORUM_POST_CREATE_SUCCESS'
export const FORUM_POST_CREATE_FAIL = 'FORUM_POST_CREATE_FAIL'

export const FORUM_POST_LIST_REQUEST = 'FORUM_POST_LIST_REQUEST'
export const FORUM_POST_LIST_SUCCESS = 'FORUM_POST_LIST_SUCCESS'
export const FORUM_POST_LIST_FAIL = 'FORUM_POST_LIST_FAIL'

export const FORUM_POST_DETAILS_REQUEST = 'FORUM_POST_DETAILS_REQUEST'
export const FORUM_POST_DETAILS_SUCCESS = 'FORUM_POST_DETAILS_SUCCESS'
export const FORUM_POST_DETAILS_FAIL = 'FORUM_POST_DETAILS_FAIL'
export const FORUM_POST_CREATE_RESET = 'FORUM_POST_CREATE_RESET';