# Generated by Django 5.1.1 on 2024-09-28 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-id']},
        ),
    ]
