# Generated by Django 5.1.1 on 2024-09-28 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_bookmark_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
