# Generated by Django 5.1.1 on 2024-10-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Not specified'), ('Appetizers & Snacks', 'Appetizers & Snacks'), ('Breakfast & Brunch', 'Breakfast & Brunch'), ('Main Dishes', 'Main Dishes'), ('Soups & Stews', 'Soups & Stews'), ('Salads', 'Salads'), ('Side Dishes', 'Side Dishes'), ('Desserts & Sweets', 'Desserts & Sweets'), ('Beverages', 'Beverages'), ('Vegan & Vegetarian', 'Vegan & Vegetarian'), ('Gluten-Free', 'Gluten-Free'), ('Low-Carb & Keto', 'Low-Carb & Keto'), ('Quick & Easy Meals', 'Quick & Easy Meals'), ('Seafood & Fish', 'Seafood & Fish'), ('Pasta & Noodles', 'Pasta & Noodles'), ('Breads & Baked Goods', 'Breads & Baked Goods'), ('Casseroles', 'Casseroles'), ('Grilling & BBQ', 'Grilling & BBQ'), ('International Cuisine', 'International Cuisine'), ('Comfort Food', 'Comfort Food'), ('Healthy Recipes', 'Healthy Recipes')], default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
